---
title: '2019-05-15'
author: "KaEDe"
date: "2019年5月15日"
output: html_document
---

```{r}
df1 <- data.frame(
  熱量= c("330cal","500cal","432cal"),
  糖分=c("50g","3g","20g"),
  酒精濃度=c(0,5,2.5)
)
df1
names(df1)[[2]] <- "sugar"
names(df1)[c(1,3)] <- c("卡路里","濃度")
df1
```

請將下面的TRUE換成FALSE, 並增加第5個元素其值為數字7。
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b[c(3,5)] <- c(F,7)

b$新元素 <- "新元素1"
b[["新元素2"]] <-"新元素2"
b

```


```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

取出「期間」變數轉成date class。
```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```

增加一個「isAsiaCrisis」的logical變數，其值為TRUE若「期間」介於1997-06-01到1998-12-01（含前後）。

```{r}
a <-as.double(ymd("1997-06-01"))
b <-as.double(ymd("1998-12-01"))
dou <- as.double(exData3$期間) 
isAsiaCrisis <- (dou-a) >=0 & (b-dou)>=0
isAsiaCrisis
```

利用「isAsiaCrisis」值，結合使用[.R,.C]取出1997-06-01到1998-12-01亞洲金融危機的子樣本。
```{r}
exData3[isAsiaCrisis,]
```





