---
title: '2019-05-22'
author: "KaEDe"
date: "2019年5月22日"
output: html_document
---

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```

```{r}
library(lubridate)
log1 <- invoiceList$訂單時區 == "Asia/Taipei"
log2 <- invoiceList$訂單時區 == "America/New_York"
tptz <-  ymd_hms(invoiceList$訂單時區之下單時間[log1],tz="Asia/Taipei")
nytz <-  ymd_hms(invoiceList$訂單時區之下單時間[log2],tz="America/New_York")
invoiceList$UTC時間[log1] <- with_tz(tptz,tzone="UTC")
invoiceList$UTC時間[log2] <- with_tz(nytz,tzone="UTC")
invoiceList
```

```{r}
ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  time1 <- ymd_hms(input,tz=fromTzone)
  answer <- with_tz(time1,tzone = toTzone)
  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```

請寫一個函數其名稱為date_convert_twYM，且date_convert_twYM(x)可以把一個民國年月字串物件x轉成date time class的西元年月日物件輸出。
```{r}
library(stringr); library(lubridate)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates

date_convert_twYM <- function(x,dd=01){
  yyyy<-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(x,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-"))
  y <- ymd(yyyymmdd)
  return(y)
}
date_convert_twYM(twDates)
```

