---
title: '2019-05-18'
author: "KaEDe"
date: "2019年5月8日"
output: html_document
---
```{r}
library(lubridate); library(stringr); library(dplyr); library(readr); library(purrr)
```

期中檢討

執行以下程式產生台灣民國年月字串物件twDates。
```{r}
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
### twDates
```

5.1 去除字元
請將twDates中的“民國”及“月”都去除，並存在twDates2答案物件，如：“民國099年2月”會變成“099年2”
```{r}
str_replace(twDates,"民國","") -> x1
x1
str_replace(x1,"月","") -> twDates2
twDates2
```



5.2 取出年份
取出民國年的並加上1911年轉成西元年，將此年份存在答案物件westYears裡（class為integer）。(hint:  str_split()可分割字串,再使用第3題取出你要的部份)

```{r}
twDates
str_sub(twDates,3,5) -> yearCharacter
yearCharacter
as.integer(yearCharacter)+1911 -> westYears
westYears
```


5.3 西元年月日
將twDates民國年月轉成date class的西元年月日，原始資料沒有日，請設定成每月1日。例如：“民國100年5月”會轉成2011-05-01的date class日期。答案請存westDates答案物件。

```{r}
twDates2
str_split(twDates2,"年") -> datesSplitList
datesSplitList

map(datesSplitList,~.[[2]]) -> monthList
monthList

unlist(monthList) -> monthVector
monthVector

str_c(as.character(westYears),monthVector,"01",sep = "-") -> westDates
westDates

ymd(westDates) -> westDates
westDates
class(westDates)
```


