---
title: '2019-04-07'
author: "KaEDe"
date: "2019年4月7日"
output: html_document
---

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```
給你一大筆資料 head代表頭6個資料
發現currency是character
轉成factor才能看levels
```{r}
head(currency)
class(currency)
levels(currency)
```


```{r}
currency <- as.factor(currency)
class(currency)
levels(currency)
```
裡面有幾種資料?
```{r}
length(levels(currency))
```

想知道一堆資料中有幾筆資料是"日圓"
利用sum函數
```{r}
sum(currency == "日圓JPY/USD")
```

練習邏輯

令adress為居住地 gender為性別 共有5筆資料
```{r}
adress <- c("新竹縣" , "新北市" , "高雄市" , "台北市" , "台北市")

gender <- c("男" , "男" , "女" , "男" , "女")

class(adress)

fac.adress <- as.factor(adress)
class(fac.adress)
```

是否居住於大台北?
```{r}
greatTaipei <- c("台北市" , "新北市")

adress %in% greatTaipei
!(adress %in% greatTaipei)

fac.adress %in% greatTaipei

```

文氏圖的概念:
居住於大台北地區的男生?
第幾筆資料符合?
```{r}
(adress %in% greatTaipei)
(gender == "男")
(adress %in% greatTaipei) & (gender == "男")
which((adress %in% greatTaipei) & (gender == "男"))
```

練習:男生或非大台北地區的人?
已知答案為1234
```{r}
adress
gender
!(adress %in% greatTaipei) | (gender == "男")
```


男生或住在大台北地區的，但是要排除住在大台北地區的男生
使用xor(男生,住在大台北)
```{r}
gender
adress
xor(gender == "男" , adress %in% greatTaipei)
```



