---
title: '2019-04-17'
author: "KaEDe"
date: "2019年4月17日"
output: html_document
---

```{r}
refrigirator <- list(
  drinkS = c("麒麟","虎牌","雪山","金牌"),
  fruit = c("蘋果","番茄","鳳梨"),
  vegetable = c("小白菜","高麗菜","菠菜","空心菜")
)
refrigirator

refrigirator[[1]]
refrigirator[["vegetable"]]
```

若只想取麒麟出來
```{r}
refrigirator[[1]][[1]]
refrigirator[["drinkS"]][[1]]
```

若想拿出所有的青菜及水果
```{r}
refrigirator[c("fruit","vegetable")]
```

用[  ] 會保有原來的class
所以出來的東西還是list
```{r}
a <- refrigirator[c("fruit","vegetable")]
aa <- refrigirator[[1]]
aaa <- refrigirator[1]
class(a)
class(aa)
class(aaa)
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
extract1 <- plasticContainer[c("greenBox")]
extract2 <- plasticContainer[[c("greenBox")]]

extract1[[1]][[1]]
extract2[[1]]
```
another way to extract

```{r}
length(refrigirator)
aba <- refrigirator[c(T,T,F)]
aba
aba[[1]]
aba[[1]][[1]]
```

使用$
$拿出來的非list 是向量
```{r}
refrigirator$drinkS
refrigirator[["drinks"]]
refrigirator[[1]]
```

```{r}
your_github_username <- "KaEDe1106"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))

commitCheckStatement

```
請取出第4個commit紀錄的commit時間（為UTC time），並轉成台灣時間。
```{r}
library(lubridate)
commitCheck[[4]][["commit"]][["committer"]][["date"]]

committime <- commitCheck[[4]]$commit$committer$date
utccommittime <- ymd_hms(committime)
utccommittime

```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```

birthday只能有8位元，str_length()可計算每個元素的位元長度。請產生一個logical vector稱為logiCorrect，TRUE表示剛好8位元。
```{r}
logiCorrect <- str_length(birthday)==8
logiCorrect
favoriteTwo[logiCorrect]

```


只留下birthday輸入正確的人，請統計各別片名支持人數。