---
title: '2019-04-10'
author: "KaEDe"
date: "2019年4月10日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
course <- c("個體經濟學","投資學","總體經濟學")

str_subset(course,"經濟學")
str_detect(course,"經濟學")
```

```{r}
drinks <- c("啤酒", "牛奶" , "高粱酒" , "優酪乳", "葡萄酒")
str_subset(drinks,"酒")
!str_detect(drinks,"酒")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')

major <-str_sub(studentID,5,6)
major
year <- str_sub(studentID,2,4) 
year
```

```{r}
hour <- c("5","18", "2" , "3")
word1 <- c("點","點","點","點")
minute <- c("22","09","59", "01")
word2 <- c("分","分","分","分")
str_c(hour , word1 , minute , word2)
str_c(hour ,"點" , minute , "分")
str_c(hour , minute , sep = ":")
```

```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
str_replace(dates,"-","月")
```

```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```
由以上可得知取代只會取代第一個，除非有all

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
username
reponame
```
將username與reponame合併成Github repo網址。
```{r}
str_c("http://github.com/",username,"/",reponame)
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`

head(birthday)
```
```{r}
year1 <-str_sub(birthday,1,4)
mounth1 <- str_sub(birthday,5,6)
day1 <- str_sub(birthday,7,8)
answer <- str_c("西元",year1,"年",mounth1,"月",day1,"日")
answer
```


```{r}
民國年月<-c("099/01","099/02","099/03")
aa <- str_sub(民國年月,1,3)
intaa <- as.integer(aa)
west <- intaa+1911
chawest <- as.character(west)
answer2 <-str_c(chawest,str_sub(民國年月,4,6))
answer2
```





