---
title: '2019-03-27'
author: "林茂廷"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
NYDateTime <- with_tz(twDateTime,tzone="America/New_York")


as.double(twDateTime)
as.double(NYDateTime)

twDateTime
NYDateTime

```


```{r}
Google <- mdy_hms("03-18-2019 14:04:00", tz="Asia/Taipei")
Google
```

```{r}
today <- ymd("2018-09-11")
today
today1 <- mdy("March 3, 2019")
today1
```

```{r}
aa <- c(2,5,-3)
bb <- c(1,5,6)
aaL <- c(2L,5L,-3L)
bbL <- c(1L,5L,6L)

aa+bb
aaL+bbL
aa+bbL
aaL+bbL
class(aa+bb)
class(aaL+bbL)
class(aa+bbL)
class(aaL+bb)

aaL*bbL
aaL/bbL
a^b
```


```{r}
twDateTime1 <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime1
twDateTime1 + 5648653123

twDT2 <- ymd_hms("2019-03-20 14:04:09", tz="Asia/Taipei")
twDT2

twDateTime1 - twDT2
as.double(twDateTime1 - twDT2)
```

```{r}
DDD <- ymd("1999-02-01")
DDD + years(100)
DDD + dyears(100)
```


