---
title: "2019-6-12"
author: "KaEDe"
date: "2019年6月12日"
output: html_document
---


任務：一一檢查gmailAddress每個元素，若沒有寫“@gmail.com”則加上。

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)

library(stringr)

for(i in seq_along(gmailAddress)){
  if(!(str_detect(gmailAddress[[i]],"@gmali.com"))){
    gmailAddress[[i]] <- str_c(gmailAddress[[i]],"@gmali.com")
  }
}
gmailAddress
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

```{r}
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]]$commit$author$name)
}
```


print每個commit的committer
```{r}
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]]$commit$committer$name)
}
```

存下來每個author與committer同人的commitDate

```{r}
for(i in seq_along(commitHistory)){
  log1 <- commitHistory[[i]]$commit$author$name == commitHistory[[i]]$commit$committer$name
  cat(log1)
}
```

創造"容器"
```{r}
saveCharacter <- vector("character",5)
saveCharacter

saveNumeric <- vector("numeric",5)
saveNumeric

saveLogical <- vector("logical",5)
saveLogical

saveList <- vector("list",5)
saveList
```

```{r}

```









