---
title: '2019-05-29'
author: "KaEDe"
date: "2019年5月29日"
output: html_document
---

```{r}
library(lubridate)
now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
now2()
```

```{r}
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/")
}
textbookURL()
```


```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")

gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
gpa_fun2("92aS67fee")
```

創造一個demand_supply_fun(P,a,b,c,d)，它會輸出一個list包含三個元素：供給量，需求量，超額供給量
```{r}
demand_supply_fun <- function(P,a,b,c,d){
  
  Qs = a+b*P
  Qd = c-d*P
  
  return(
    list(
      供給量 = Qs,
      需求量 = Qd,
      超額供給量 = Qs-Qd
    )
  )
}

```

依條件執行

```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P cannot be negative") 
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```

gpa_fun, 若輸入學號不存在則在螢幕顯示“查無此學號”。
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")

gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
    transcriptDataFinal$學號==studentID -> logiChosenStudent
    subSample <- transcriptDataFinal[logiChosenStudent,]
    sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
    return(GPA)
  }else{
    message("cannot find the studend ID")
  }
  
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P cannot be negative") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P must be larger than",-a/b,"(-a/b)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=3,-3,1)
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)

```

```{r}
fizzbuzz <- function(input){
  if(input %% 15 == 0 ){
    print("fizzbuzz")
  }else if(input %% 3 == 0){
    print("fizz")
  }else if(input %% 5 == 0){
    print("buzz")
  }else {
    print(input)
  }
}

fizzbuzz(15)
fizzbuzz(6)
fizzbuzz(4)
fizzbuzz(20)
```










