---
title: '2019-06-05'
author: "KaEDe"
date: "2019年6月5日"
output: html_document
---

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
utility_cobb_douglass(.beta=0.8,2,0.5,x=1)
```

```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
# 以前5筆學號為sequence_source
studentIds5 <- studentIds[1:5]
```


```{r}
for(i in studentIds5){
  print(i) # 印出studentIds5[[i]]
}
```

```{r}
for(i in c(1:5)){
   print(i) 
  print(studentIds5[[i]]) # 
}
```

```{r}
seq_along(studentIds5)

for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

一一檢查gmailAddress每個元素，若沒有寫"@gmail.com"則加上。
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)

library(stringr)

for(i in seq_along(gmailAddress)){
  if(!(str_detect(gmailAddress[[i]],"@gmali.com"))){
    gmailAddress[[i]] <- str_c(gmailAddress[[i]],"@gmali.com")
  }
}
gmailAddress
```

```{r}
library(stringr)

for(i in seq_along(gmailAddress)){
  if(!(str_detect(gmailAddress[[i]],"@gmali.com"))){
    gmailAddress[[i]] <- str_c(gmailAddress[[i]],"@gmali.com")
  }
}
gmailAddress

```

















